name: Magadha
favicon: null
layout_spectrum: 0.9425982006359845
typography_spectrum: 0.12834033905528486
title: Buddhist India
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#201d18'
    - '#636057'
    - '#d7bba6'
    - '#eb6b35'
  brandStrength: 0.9846162579488009
  lightness: 0.44328866130672395
  saturation: 0.6648299302905798
  rhythmicContrast: 0.9246308747678995
purpose: []
